# FILES AND FOLDERS

folders:
  auto_root: "~/OneDrive/Projects/Maps/GPS/Auto"
  import_root: "~/OneDrive/Import/"
  raw:
    bad_elf: "raw/bad_elf"
    mytracks: "raw/mytracks"

files:
  canonical_kml: "driving_canonical.kml"
  canonical_backup: "./.backup/driving_canonical.backup.kml"
  output_kmz: "Driving.kmz"


# TIMESTAMP FORMATS

timestamps:
  kml_name: "%Y-%m-%d %H:%M:%SZ"
  raw:
    bad_elf: "%Y%m%dT%H%M%SZ"
    mytracks: "%Y%m%dT%H%M%SZ"


# IMPORT CONFIGURATION

import:

  min_points: 1 # Only keep linestrings with at least this many points
  
  gpx:
    
    _default:
      merge_segments:
        enabled: false
      trim:
        enabled: false
      simplify:
        enabled: false

    bad_elf:
      merge_segments:
        enabled: false
      trim:
        enabled: true
      simplify:
        enabled: true
        epsilon: 0.000002

    garmin:
      merge_segments:
        enabled: true
        max_seconds: 600
      trim:
        enabled: false
      simplify:
        enabled: false
    
    mytracks:
      merge_segments:
        enabled: false
      trim:
        enabled: false
      simplify:
        enabled: true
        epsilon: 0.000002

  # Tracks and track segments to ignore when importing. Tracks and track segments are identified by a UTC timestamp of their first waypoint.
  ignore:
    trk:
      # GPX Tracks to ignore.
      - "2015-10-11T15:37:00+00:00"
      - "2016-05-06T15:40:01+00:00"
      - "2016-05-06T22:59:02+00:00"
      - "2016-05-07T02:00:00+00:00"
      - "2016-09-02T19:18:05+00:00"
      - "2017-07-15T21:58:02+00:00"
      - "2017-09-19T22:50:46+00:00"
      - "2017-12-19T03:44:05+00:00"
      - "2018-03-30T14:27:05+00:00"
      - "2018-04-16T20:16:58+00:00"
      - "2018-04-18T21:53:16+00:00"
      - "2018-05-17T23:31:20+00:00"
      - "2018-06-12T23:01:29+00:00"
      - "2018-06-12T23:51:41+00:00"
      - "2018-06-13T00:20:59+00:00"
      - "2018-12-08T15:53:00+00:00"
      - "2019-04-25T01:23:08+00:00"
      - "2019-08-18T14:11:48+00:00"
      - "2019-09-01T19:46:33+00:00"
      - "2020-07-06T23:23:54+00:00"
      - "2020-07-25T16:00:50+00:00"
      - "2021-08-02T16:14:10+00:00"
      - "2021-08-02T19:04:43+00:00"
      - "2021-08-02T19:50:55+00:00"
      - "2021-10-11T03:18:43+00:00"
      - "2021-10-11T04:15:42+00:00"
      - "2022-01-10T16:49:29+00:00" # Track has offset error
      - "2022-04-01T01:12:56+00:00" # Amy driving
    trkseg:
      # Individual track segments to ignore. (All track segments in a track ignored above will also be ignored.)      
      - "2021-10-03T18:31:26-04:00"